[package]
name = "crfsuite"
version = "0.1.0-pre"
authors = ["Thibaut Lorrain <thibaut.lorrain@snips.ai>"]

[dependencies]
error-chain = { version = "0.10", default-features=false }
libc = "0.2"
crfsuite-sys = { path = "crfsuite-sys" }

[workspace]

