[package]
name = "crfsuite-rs-binding"
version = "0.1.0-pre"
authors = ["Thibaut Lorrain <thibaut.lorrain@snips.ai>"]
build = "build.rs"

[build-dependencies]
gcc = "0.3"
bindgen = "0.20"

[dependencies]
error-chain = { version = "0.10", default-features=false }
libc = "0.2"



