[package]
name = "crfsuite"
version = "0.2.0-pre"
authors = ["Thibaut Lorrain <thibaut.lorrain@snips.ai>"]

[dependencies]
failure = "0.1"
libc = "0.2"
crfsuite-sys = { path = "crfsuite-sys" }

[workspace]

