[package]
name = "crfsuite-sys"
version = "0.4.1"
authors = ["Thibaut Lorrain <thibaut.lorrain@snips.ai>"]
edition = "2018"
links = "crfsuite"

[build-dependencies]
cc = "1.0"
bindgen = "0.56"
dinghy-build = "0.4.21"

[dependencies]
libc = "0.2"
