[package]
name = "crfsuite-sys"
version = "0.3.1-pre"
authors = ["Thibaut Lorrain <thibaut.lorrain@snips.ai>"]
edition = "2018"
links = "crfsuite"

[build-dependencies]
cc = "1.0"
bindgen = "^0.47"
dinghy-build = { version = "0.4", features = [ "with-bindgen" ] }

[dependencies]
libc = "0.2"
