[package]
name = "crfsuite-sys"
version = "0.1.0"
authors = ["Thibaut Lorrain <thibaut.lorrain@snips.ai>"]
build = "build.rs"

[build-dependencies]
gcc = "0.3"
bindgen = "0.20"

[dependencies]
libc = "0.2"

